#! /usr/bin/env python
# -*- coding: utf-8 -*-

# @Author: ${CREATE_BY}
# @Time: ${CREATE_TIME}
# @File: ${table}.py

import lib.dao.${table}_mysql as ${table}_mysql
import lib.dao.${table}_redis as ${table}_redis
import lib.common.const as com_const
import lib.common.error as error_const
import lib.common.func as com_func
from sqlalchemy import  or_, and_, any_, text, exists, func, distinct, between, case

from lib.model.model import ${Table}

# 注意所有的sql都传列表类型
### add func #####

async def add_${table}(obj):
    await ${table}_mysql.add_${table}(
        data_obj=obj
    )

async def bulk_add_${table}(data_list):
    await ${table}_mysql.bulk_add_${table}(data_list=data_list)

### add func #####

### delete func #####
async def delete_${table}(${table}_id=-1):
    filters = []
    if ${table}_id != -1:
        filters.append(${Table}.${table}_id == ${table}_id)
    # ${table}_mysql.delete_${table}(
    #     filters=filters
    # )
    await ${table}_mysql.update_${table}(
        filters=filters,
        data_dict={
            'is_delete': 1,
            'mtime': com_func.get_ts()
        }
    )

### delete func #####

### update func #####
async def update_${table}(${table}_id=-1, data_dict={}):
    filters = []
    if ${table}_id != -1:
        filters.append(${Table}.${table}_id == ${table}_id)
    await ${table}_mysql.update_${table}(
        filters=filters,
        data_dict=data_dict
    )

async def bulk_update_${table}(data_list):
    await ${table}_mysql.bulk_update_${table}(data_list=data_list)

### update func #####

### get one data func #####
async def get_${table}(${table}_id=-1):
    filters = [${Table}.is_delete == 0]
    if ${table}_id != -1:
        filters.append(${Table}.${table}_id == ${table}_id)
    data = await ${table}_mysql.get_${table}(
        query_list=[${Table}],
        filters=filters,
    )
    return data

### get one data func #####

### get data_list func #####
async def get_${table}_list_all(${table}_id_list=-1):
    filters = [${Table}.is_delete == 0]
    if ${table}_id_list != -1:
        filters.append(${Table}.${table}_id.in_(${table}_id_list))
    order_by = [${Table}.ctime.desc()]
    data_list = await ${table}_mysql.get_${table}_list(
        query_list=[${Table}],
        filters=filters,
        order_by=order_by,
    )
    return data_list


async def get_fields_${table}_list_all(fields=[],${table}_id_list=-1):
    if not fields:  # 注意重名多表字段取出的重名问题
        return []
    filters = [${Table}.is_delete == 0]
    if ${table}_id_list != -1:
        filters.append(${Table}.${table}_id.in_(${table}_id_list))
    order_by = [${Table}.ctime.desc()]
    data_list = await ${table}_mysql.get_${table}_list(
        query_list=[${Table}],
        filters=filters,
        order_by=order_by,
    )
    if len(fields) == 1:
        return data_list  # 一般是取列表
    else:
        name_list = []
        for info in fields:
            key = info.key
            if key not in name_list:
                name_list.append(key)  # test_id
            else:
                name_list.append(info.expression)  # test.test_id
        name_list = [info.key for info in fields]
        res = [dict(zip(name_list, data)) for data in data_list]
        return res


async def get_fields_${table}_list(fields=[], ${table}_id_list=-1, page=1, pagesize=10):
    if not fields:  # 注意重名多表字段取出的重名问题
        return []
    filters = [${Table}.is_delete == 0]
    if ${table}_id_list != -1:
        filters.append(${Table}.${table}_id.in_(${table}_id_list))
    order_by = [${Table}.ctime.desc()]
    data_list = await ${table}_mysql.get_${table}_list(
        query_list=[${Table}],
        filters=filters,
        order_by=order_by,
        offset=pagesize * int(page - 1),
        limit=pagesize
    )
    if len(fields) == 1:
        return data_list  # 一般是取列表
    else:
        name_list = []
        for info in fields:
            key = info.key
            if key not in name_list:
                name_list.append(key)
            else:
                name_list.append(info.expression)
        name_list = [info.key for info in fields]
        res = [dict(zip(name_list, data)) for data in data_list]
        return res



async def get_${table}_list(${table}_id_list=-1, page=1, pagesize=10):
    filters = [${Table}.is_delete == 0]
    if ${table}_id_list != -1:
        filters.append(${Table}.${table}_id.in_(${table}_id_list))
    order_by = [${Table}.ctime.desc()]
    data_list = await ${table}_mysql.get_${table}_list(
        query_list=[${Table}],
        filters=filters,
        order_by=order_by,
        offset=pagesize * int(page - 1),
        limit=pagesize
    )
    return data_list


async def get_${table}_list_count(${table}_id_list=-1):
    filters = [${Table}.is_delete == 0]
    if ${table}_id_list != -1:
        filters.append(${Table}.${table}_id.in_(${table}_id_list))
    count = await ${table}_mysql.get_${table}_list_count(
        query_list=[func.count(${Table}.${table}_id)],
        filters=filters,
    )
    return count


### get data_list func #####
