#! /usr/bin/env python
# -*- coding: utf-8 -*-

# @Author: ${CREATE_BY}
# @Time: ${CREATE_TIME}
# @File: ${table}_redis.py

from lib.common.redis_key import ${Table}Redis
from lib.common.redis_util import redis_client
from lib.common.func import serialize, deserialize


async def set_${table}_cache(key, data):
    await redis_client.set_str_cache(key=${Table}Redis.UNIQUE_KEY.format(key), str=serialize(data), ex=${Table}Redis.EX)


async def get_${table}_cache(key):
    data = await redis_client.get_str_cache(key=${Table}Redis.UNIQUE_KEY.format(key))
    if data:
        data = deserialize(data)
    else:
        data = {}
    return data


async def delete_${table}_cache(key):
    await redis_client.delete_cache(key=${Table}Redis.UNIQUE_KEY.format(key))
